package Form;

import Tabbed.TabbedForm;
import Processor.*;
import java.util.List;
import java.util.ArrayList;
import javax.swing.ButtonModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author blesDev
 */
public class EducationalBG extends TabbedForm {
    private final Misc.schoolYear YearArr = new Misc.schoolYear();
    private final Misc.SchoolNames School = new Misc.SchoolNames();
    private final Border[] shsAbarTxt = {javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(), javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "Add SHS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 18), new java.awt.Color(255, 255, 255))),
                                         javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(), javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "Update SHS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 18), new java.awt.Color(255, 255, 255)))}; 
    private final Border[] jhsAbarTxt = {javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(), javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "Add JHS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 18), new java.awt.Color(255, 255, 255))),
                                         javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(), javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "Update JHS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 18), new java.awt.Color(255, 255, 255)))};
    private int point;
    private Boolean didClick = false;
    private int prevPoint;
    private List<String> data = new ArrayList<>();
    /**
     * Creates new form TestForm
     */
    
    public EducationalBG() {
        initComponents();
        
        YearArr.setMark(2000);
        panelEditinglbl.setVisible(false);
        lblEdit.setVisible(false);
        lblRow.setVisible(false);
        // ComboBoxes setters
//        System.out.print(String.valueOf(School.fetchList()));
//        //cmbSchoolName.setModel(new DefaultComboBoxModel<>((String[]) School.fetchSql().toArray(new String[0])));
//        cmbSchoolName.setSelectedIndex(5);
//        cmbYearSHS.setModel(new DefaultComboBoxModel<>((String[]) YearArr.getYearArr().toArray(new String[0])));
//        cmbYearJHS.setModel(new DefaultComboBoxModel<>((String[]) YearArr.getYearArr().toArray(new String[0])));
//        cmbYearSHS.setSelectedIndex(YearArr.getArrEndIndex());
//        //cmbYearJHS.setSelectedIndex(YearArr.getArrEndIndex());
        
        // Buttons setters
        btnCancelJHS.setVisible(false);
        btnCancel.setVisible(false);
        
        // RadioButtons Setters
        rbCompleter.setActionCommand("Completer");
        rbIrregular.setActionCommand("Irregular");
        rbSem1.setActionCommand("1st");
        rbSem2.setActionCommand("2nd");
        rbCompleterJHS.setActionCommand("Completer");
        rbRepeaterJHS.setActionCommand("Repeater");
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BGsem = new javax.swing.ButtonGroup();
        BGremarksSHS = new javax.swing.ButtonGroup();
        BGtransferred = new javax.swing.ButtonGroup();
        BGremarksJHS = new javax.swing.ButtonGroup();
        top = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tabbedPane = new javax.swing.JTabbedPane();
        tabbedSHS = new javax.swing.JPanel();
        shsActionBar = new javax.swing.JPanel();
        lblSY = new javax.swing.JLabel();
        lblStrand = new javax.swing.JLabel();
        cmbAdviser = new javax.swing.JComboBox<>();
        cmbStrand = new javax.swing.JComboBox<>();
        lblSection = new javax.swing.JLabel();
        cmbSection = new javax.swing.JComboBox<>();
        lblGradeLevel = new javax.swing.JLabel();
        cmbGradeLevel = new javax.swing.JComboBox<>();
        rbSem2 = new javax.swing.JRadioButton();
        rbSem1 = new javax.swing.JRadioButton();
        lblRemarks = new javax.swing.JLabel();
        lblAdviser = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        rbIrregular = new javax.swing.JRadioButton();
        rbCompleter = new javax.swing.JRadioButton();
        lblSem = new javax.swing.JLabel();
        rbTransIN = new javax.swing.JRadioButton();
        rbTransOut = new javax.swing.JRadioButton();
        lblTransferred = new javax.swing.JLabel();
        cmbYearSHS = new javax.swing.JComboBox<>();
        btnAdd = new javax.swing.JButton();
        panelEditinglbl = new javax.swing.JPanel();
        lblEdit = new javax.swing.JLabel();
        lblRow = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSHS = new javax.swing.JTable();
        tabbedJHS = new javax.swing.JPanel();
        jhsActionBar = new javax.swing.JPanel();
        cmbSchoolName = new javax.swing.JComboBox<>();
        cmbRemarksJHS = new javax.swing.JLabel();
        btnAddJHS = new javax.swing.JButton();
        rbCompleterJHS = new javax.swing.JRadioButton();
        rbRepeaterJHS = new javax.swing.JRadioButton();
        lblGradeLevelJHS = new javax.swing.JLabel();
        cmbYearJHS = new javax.swing.JComboBox<>();
        lblBirthStreetAddr21 = new javax.swing.JLabel();
        lblSectionJHS = new javax.swing.JLabel();
        txtSection = new javax.swing.JTextField();
        lblAdviserJHS = new javax.swing.JLabel();
        txtAdviser = new javax.swing.JTextField();
        lblSchoolName = new javax.swing.JLabel();
        cmbGradeLevelJHS = new javax.swing.JComboBox<>();
        btnCancelJHS = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblJHS = new javax.swing.JTable();

        setBackground(new java.awt.Color(0, 171, 65));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        top.setBackground(new java.awt.Color(0, 134, 49));
        top.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        top.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Mnhs_transSmall.png"))); // NOI18N
        top.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Transparent.png"))); // NOI18N
        top.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 20, -1, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Cambria", 3, 55)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Educational Background");
        top.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 620, 80));

        add(top, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1310, 130));

        tabbedPane.setBackground(new java.awt.Color(0, 134, 49));
        tabbedPane.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tabbedPane.setForeground(new java.awt.Color(255, 255, 255));
        tabbedPane.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        tabbedPane.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        tabbedPane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tabbedPane.setFont(new java.awt.Font("Times New Roman", 2, 20)); // NOI18N
        tabbedPane.setOpaque(true);

        tabbedSHS.setBackground(new java.awt.Color(0, 171, 65));
        tabbedSHS.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tabbedSHS.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        shsActionBar.setBackground(new java.awt.Color(0, 134, 49));
        shsActionBar.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(), javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "Add SHS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 18), new java.awt.Color(255, 255, 255)))); // NOI18N
        shsActionBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSY.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lblSY.setForeground(new java.awt.Color(255, 255, 255));
        lblSY.setText("School Year");
        shsActionBar.add(lblSY, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 110, -1));

        lblStrand.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lblStrand.setForeground(new java.awt.Color(255, 255, 255));
        lblStrand.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStrand.setText("Strand ");
        shsActionBar.add(lblStrand, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 100, -1));

        cmbAdviser.setBackground(new java.awt.Color(192, 245, 182));
        cmbAdviser.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cmbAdviser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        cmbAdviser.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        shsActionBar.add(cmbAdviser, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 300, 30));

        cmbStrand.setBackground(new java.awt.Color(192, 245, 182));
        cmbStrand.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cmbStrand.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "I.C.T", "S.T.E.M", "G.A.S", "H.E", "A.D.A.S" }));
        cmbStrand.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        shsActionBar.add(cmbStrand, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 100, 30));

        lblSection.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lblSection.setForeground(new java.awt.Color(255, 255, 255));
        lblSection.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSection.setText("Section");
        shsActionBar.add(lblSection, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 60, -1));

        cmbSection.setBackground(new java.awt.Color(192, 245, 182));
        cmbSection.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cmbSection.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06" }));
        cmbSection.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        shsActionBar.add(cmbSection, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 80, 30));

        lblGradeLevel.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lblGradeLevel.setForeground(new java.awt.Color(255, 255, 255));
        lblGradeLevel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGradeLevel.setText("Grade Level");
        shsActionBar.add(lblGradeLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 110, -1));

        cmbGradeLevel.setBackground(new java.awt.Color(192, 245, 182));
        cmbGradeLevel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cmbGradeLevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "11", "12" }));
        cmbGradeLevel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        shsActionBar.add(cmbGradeLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 90, 30));

        BGsem.add(rbSem2);
        rbSem2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        rbSem2.setForeground(new java.awt.Color(255, 255, 255));
        rbSem2.setText("2nd");
        rbSem2.setName("2nd"); // NOI18N
        shsActionBar.add(rbSem2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, -1, 20));

        BGsem.add(rbSem1);
        rbSem1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        rbSem1.setForeground(new java.awt.Color(255, 255, 255));
        rbSem1.setText("1st");
        rbSem1.setName("1st"); // NOI18N
        shsActionBar.add(rbSem1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, -1, 20));

        lblRemarks.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lblRemarks.setForeground(new java.awt.Color(255, 255, 255));
        lblRemarks.setText("Remarks");
        shsActionBar.add(lblRemarks, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 70, -1));

        lblAdviser.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lblAdviser.setForeground(new java.awt.Color(255, 255, 255));
        lblAdviser.setText("Adviser");
        shsActionBar.add(lblAdviser, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 70, -1));

        btnCancel.setBackground(new java.awt.Color(192, 245, 182));
        btnCancel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnCancel.setName("CancelButton"); // NOI18N
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        shsActionBar.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 90, 30));

        BGremarksSHS.add(rbIrregular);
        rbIrregular.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        rbIrregular.setForeground(new java.awt.Color(255, 255, 255));
        rbIrregular.setText("Irregular");
        rbIrregular.setName("Repeater"); // NOI18N
        shsActionBar.add(rbIrregular, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        BGremarksSHS.add(rbCompleter);
        rbCompleter.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        rbCompleter.setForeground(new java.awt.Color(255, 255, 255));
        rbCompleter.setText("Completer");
        rbCompleter.setName("Completer"); // NOI18N
        shsActionBar.add(rbCompleter, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        lblSem.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lblSem.setForeground(new java.awt.Color(255, 255, 255));
        lblSem.setText("Semester");
        shsActionBar.add(lblSem, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 80, -1));

        BGtransferred.add(rbTransIN);
        rbTransIN.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        rbTransIN.setForeground(new java.awt.Color(255, 255, 255));
        rbTransIN.setText("Transferred-In");
        rbTransIN.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        rbTransIN.setName("Transferred In"); // NOI18N
        shsActionBar.add(rbTransIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, -1));

        BGtransferred.add(rbTransOut);
        rbTransOut.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        rbTransOut.setForeground(new java.awt.Color(255, 255, 255));
        rbTransOut.setText("Transferred-Out");
        rbTransOut.setName("Transferred Out"); // NOI18N
        shsActionBar.add(rbTransOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, -1, -1));

        lblTransferred.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lblTransferred.setForeground(new java.awt.Color(255, 255, 255));
        lblTransferred.setText("Transferred");
        shsActionBar.add(lblTransferred, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 90, -1));

        cmbYearSHS.setBackground(new java.awt.Color(192, 245, 182));
        cmbYearSHS.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cmbYearSHS.setSelectedIndex(YearArr.getArrEndIndex());
        cmbYearSHS.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        shsActionBar.add(cmbYearSHS, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 130, 30));

        btnAdd.setBackground(new java.awt.Color(192, 245, 182));
        btnAdd.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnAdd.setName("AddButton"); // NOI18N
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        shsActionBar.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 90, 30));

        tabbedSHS.add(shsActionBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 340, 420));

        panelEditinglbl.setBackground(new java.awt.Color(0, 134, 49));
        panelEditinglbl.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelEditinglbl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblEdit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblEdit.setForeground(new java.awt.Color(255, 255, 255));
        lblEdit.setText("Currently Editing Row:");
        panelEditinglbl.add(lblEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 20));

        lblRow.setFont(new java.awt.Font("Javanese Text", 1, 14)); // NOI18N
        lblRow.setForeground(new java.awt.Color(255, 255, 255));
        lblRow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelEditinglbl.add(lblRow, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 30, 20));

        tabbedSHS.add(panelEditinglbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 210, 20));

        jPanel4.setBackground(new java.awt.Color(0, 134, 49));
        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblSHS.setBackground(new java.awt.Color(153, 255, 153));
        tblSHS.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblSHS.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tblSHS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "S.Y", "Semester", "Section", "Grade Level", "Strand", "Remarks", "Adviser"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSHS.setToolTipText("");
        tblSHS.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        tblSHS.setGridColor(new java.awt.Color(0, 134, 49));
        tblSHS.setName("SHS_table"); // NOI18N
        tblSHS.setShowGrid(true);
        tblSHS.getTableHeader().setResizingAllowed(false);
        tblSHS.getTableHeader().setReorderingAllowed(false);
        tblSHS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSHSMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSHS);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 740, 420));

        tabbedSHS.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 760, 460));

        tabbedPane.addTab("SHS", null, tabbedSHS, "");

        tabbedJHS.setBackground(new java.awt.Color(0, 171, 65));
        tabbedJHS.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tabbedJHS.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tabbedJHS.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jhsActionBar.setBackground(new java.awt.Color(0, 134, 49));
        jhsActionBar.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(), javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), "Add JHS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 18), new java.awt.Color(255, 255, 255)))); // NOI18N
        jhsActionBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbSchoolName.setBackground(new java.awt.Color(192, 245, 182));
        cmbSchoolName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cmbSchoolName.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        cmbSchoolName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSchoolNameActionPerformed(evt);
            }
        });
        jhsActionBar.add(cmbSchoolName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 290, 30));

        cmbRemarksJHS.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        cmbRemarksJHS.setForeground(new java.awt.Color(255, 255, 255));
        cmbRemarksJHS.setText("Remarks");
        jhsActionBar.add(cmbRemarksJHS, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 70, -1));

        btnAddJHS.setBackground(new java.awt.Color(192, 245, 182));
        btnAddJHS.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnAddJHS.setText("Add");
        btnAddJHS.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnAddJHS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddJHSActionPerformed(evt);
            }
        });
        jhsActionBar.add(btnAddJHS, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 90, 30));

        BGremarksJHS.add(rbCompleterJHS);
        rbCompleterJHS.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        rbCompleterJHS.setForeground(new java.awt.Color(255, 255, 255));
        rbCompleterJHS.setText("Completer");
        rbCompleterJHS.setName("Completer"); // NOI18N
        rbCompleterJHS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCompleterJHSActionPerformed(evt);
            }
        });
        jhsActionBar.add(rbCompleterJHS, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, -1, -1));

        BGremarksJHS.add(rbRepeaterJHS);
        rbRepeaterJHS.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        rbRepeaterJHS.setForeground(new java.awt.Color(255, 255, 255));
        rbRepeaterJHS.setText("Repeater");
        rbRepeaterJHS.setName("Repeater"); // NOI18N
        jhsActionBar.add(rbRepeaterJHS, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, -1, -1));

        lblGradeLevelJHS.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lblGradeLevelJHS.setForeground(new java.awt.Color(255, 255, 255));
        lblGradeLevelJHS.setText("Grade Level");
        jhsActionBar.add(lblGradeLevelJHS, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        cmbYearJHS.setBackground(new java.awt.Color(192, 245, 182));
        cmbYearJHS.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cmbYearJHS.setSelectedIndex(YearArr.getArrEndIndex());
        jhsActionBar.add(cmbYearJHS, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 180, 30));

        lblBirthStreetAddr21.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lblBirthStreetAddr21.setForeground(new java.awt.Color(255, 255, 255));
        lblBirthStreetAddr21.setText("School Year");
        jhsActionBar.add(lblBirthStreetAddr21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 100, -1));

        lblSectionJHS.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lblSectionJHS.setForeground(new java.awt.Color(255, 255, 255));
        lblSectionJHS.setText("Section");
        jhsActionBar.add(lblSectionJHS, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        txtSection.setBackground(new java.awt.Color(192, 245, 182));
        txtSection.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtSection.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jhsActionBar.add(txtSection, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 180, 30));

        lblAdviserJHS.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lblAdviserJHS.setForeground(new java.awt.Color(255, 255, 255));
        lblAdviserJHS.setText("Adviser");
        jhsActionBar.add(lblAdviserJHS, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        txtAdviser.setBackground(new java.awt.Color(192, 245, 182));
        txtAdviser.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtAdviser.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jhsActionBar.add(txtAdviser, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 290, 30));

        lblSchoolName.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        lblSchoolName.setForeground(new java.awt.Color(255, 255, 255));
        lblSchoolName.setText("School Name");
        jhsActionBar.add(lblSchoolName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        cmbGradeLevelJHS.setBackground(new java.awt.Color(192, 245, 182));
        cmbGradeLevelJHS.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cmbGradeLevelJHS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10" }));
        cmbGradeLevelJHS.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        cmbGradeLevelJHS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbGradeLevelJHSActionPerformed(evt);
            }
        });
        jhsActionBar.add(cmbGradeLevelJHS, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 180, 30));

        btnCancelJHS.setBackground(new java.awt.Color(192, 245, 182));
        btnCancelJHS.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnCancelJHS.setText("Cancel");
        btnCancelJHS.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnCancelJHS.setName("CancelButton"); // NOI18N
        btnCancelJHS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelJHSActionPerformed(evt);
            }
        });
        jhsActionBar.add(btnCancelJHS, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 90, 30));

        tabbedJHS.add(jhsActionBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 340, 420));

        jPanel5.setBackground(new java.awt.Color(0, 134, 49));
        jPanel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblJHS.setBackground(new java.awt.Color(153, 255, 153));
        tblJHS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "S.Y", "School Name", "Grade Level", "Section", "Remarks", "Adviser"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblJHS.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tblJHS.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        tblJHS.setGridColor(new java.awt.Color(0, 134, 49));
        tblJHS.setShowGrid(true);
        tblJHS.getTableHeader().setReorderingAllowed(false);
        tblJHS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblJHSMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblJHS);

        jPanel5.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 740, 420));

        tabbedJHS.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 760, 460));

        tabbedPane.addTab("JHS", tabbedJHS);

        add(tabbedPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 1250, 500));
        tabbedPane.getAccessibleContext().setAccessibleName("");
        tabbedPane.getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddJHSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddJHSActionPerformed
        // TODO add your handling code here:
//        String txt = btnAddJHS.getText();
//        
//        if(txt.equals("Add")){
//            int Option = JOptionPane.showConfirmDialog(null, "Add New Junior-High Data to Table?", "Adding..", JOptionPane.YES_NO_OPTION);
//            if(Option == 0){
//                if(BGremarksJHS.isSelected(rbCompleterJHS.getModel()) == false && BGremarksJHS.isSelected(rbRepeaterJHS.getModel()) == false){
//                    JOptionPane.showMessageDialog(this, "One of the fields are null/left blank.", "Invalid Field", 
//                            JOptionPane.INFORMATION_MESSAGE);
//                }else{
//                    String SY = String.valueOf(cmbYearJHS.getSelectedItem());
//                    String schoolName = "LakeView Integrated School";
//                    String Section = txtSection.getText();
//                    String Adviser = txtAdviser.getText();
//                    String Remarks = BGremarksJHS.getSelection().getActionCommand();
//                
//                    Object[] data = {SY, schoolName,
//                                     Section, Remarks, Adviser};
//                    DefaultTableModel jhsModel = (DefaultTableModel) tblJHS.getModel();
//                    jhsModel.addRow(data);
//                }
//            }
//        }else{
//            int Option = JOptionPane.showConfirmDialog(null, "Update Junior-High Data to Table?", "Updating..", JOptionPane.YES_NO_OPTION);
//            if(Option == 0){
//                
//                if(BGremarksJHS.isSelected(rbCompleterJHS.getModel()) == false && BGremarksJHS.isSelected(rbRepeaterJHS.getModel()) == false){
//                    JOptionPane.showMessageDialog(this, "One of the fields are null/left blank.", "Invalid Field", 
//                            JOptionPane.INFORMATION_MESSAGE);
//                }else{
//                    String SY = String.valueOf(cmbYearJHS.getSelectedItem());
//                    String schoolName = "LakeView Integrated School";
//                    String Section = txtSection.getText();
//                    String Adviser = txtAdviser.getText();
//                    String Remarks = BGremarksJHS.getSelection().getActionCommand();
//                
//                    Object[] data = {SY, schoolName,
//                                     Section, Remarks, Adviser};
//                    //DefaultTableModel jhsModel = (DefaultTableModel) tblJHS.getModel();
//                    //jhsModel.addRow(data);
//                    btnAddJHS.setText("Add");
//                    btnCancelJHS.setVisible(false);
//                    jhsActionBar.setBorder(jhsAbarTxt[0]);
//                }
//                
//            }
//        }
    }//GEN-LAST:event_btnAddJHSActionPerformed

    private void tblSHSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSHSMouseClicked
        // TODO add your handling code here:
        point = tblSHS.rowAtPoint(evt.getPoint());
        DefaultTableModel shsModel = (DefaultTableModel) tblSHS.getModel();
        
        if(didClick == true && !(point == prevPoint)){
            int Option = JOptionPane.showConfirmDialog(null, "You are currently editing row "+prevPoint+", Are you sure to change rows?.", "Currently Editing", JOptionPane.YES_NO_OPTION);
            
            if(Option == 0){
                prevPoint = point;
                panelEditinglbl.setVisible(true);
                lblEdit.setVisible(true);
                lblRow.setText(String.valueOf(point));
                lblRow.setVisible(true);
                shsActionBar.setBorder(shsAbarTxt[1]);
                btnAdd.setText("Update");
                btnCancel.setVisible(true);
                
                data.clear();
                for(int i = 0; i < shsModel.getColumnCount(); i++){
                    data.add(String.valueOf(shsModel.getValueAt(point, i)));
                }
                // Display
                cmbSection.setSelectedItem(data.get(2));
                cmbGradeLevel.setSelectedItem(data.get(3));
                cmbStrand.setSelectedItem(data.get(4));
                cmbYearSHS.setSelectedItem(data.get(0));
                
                ButtonModel btn = data.contains("1st") ? rbSem1.getModel() : rbSem2.getModel();
                BGsem.setSelected(btn, true);
                ButtonModel _btn = data.contains("Completer") ? rbCompleter.getModel() : rbIrregular.getModel();
                BGremarksSHS.setSelected(_btn, true);
                
            }
            
        }else{
            didClick = true;
            prevPoint = point;
            
            // Miscellaneous
            panelEditinglbl.setVisible(true);
            lblEdit.setVisible(true);
            lblRow.setText(String.valueOf(point));
            lblRow.setVisible(true);
            shsActionBar.setBorder(shsAbarTxt[1]);
            btnAdd.setText("Update");
            btnCancel.setVisible(true);
            
            
            if(data.isEmpty()){
                for(int i = 0; i < shsModel.getColumnCount(); i++){
                    data.add(String.valueOf(shsModel.getValueAt(point, i)));
                }
                // Display
                cmbSection.setSelectedItem(data.get(2));
                cmbGradeLevel.setSelectedItem(data.get(3));
                cmbStrand.setSelectedItem(data.get(4));
                cmbYearSHS.setSelectedItem(data.get(0));
                
                ButtonModel btn = data.contains("1st") ? rbSem1.getModel() : rbSem2.getModel();
                BGsem.setSelected(btn, true);
                ButtonModel _btn = data.contains("Completer") ? rbCompleter.getModel() : rbIrregular.getModel();
                BGremarksSHS.setSelected(_btn, true);
            }
        }
        
        
    }//GEN-LAST:event_tblSHSMouseClicked

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        didClick = false;
        
        data.clear();
        panelEditinglbl.setVisible(false);
        lblEdit.setVisible(false);
        lblRow.setVisible(false);
        btnAdd.setText("Add");
        shsActionBar.setBorder(shsAbarTxt[0]);
        btnCancel.setVisible(false);
        
        cmbYearSHS.setSelectedIndex(YearArr.getArrEndIndex());
        cmbSection.setSelectedIndex(0);
        cmbGradeLevel.setSelectedIndex(0);
        cmbStrand.setSelectedIndex(0);
        BGsem.clearSelection();
        BGremarksSHS.clearSelection();
                
        
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        String txt = btnAdd.getText();
        int pointAt = point;
        
        if(txt.equals("Add")){
            // added block for add event
            int Option = JOptionPane.showConfirmDialog(null, "Add New Senior-High Data to Table?", "Adding..", JOptionPane.YES_NO_OPTION);
            if(Option == 0){
                if((BGsem.isSelected(rbSem1.getModel()) == false && BGsem.isSelected(rbSem2.getModel()) == false)|| 
              (BGremarksSHS.isSelected(rbCompleter.getModel()) == false && BGremarksSHS.isSelected(rbIrregular.getModel()) == false)){
                    
                    JOptionPane.showMessageDialog(this, "One of the fields are null/left blank.", "Invalid Field", 
                    JOptionPane.INFORMATION_MESSAGE);
                }else{
                    String SY = String.valueOf(cmbYearSHS.getSelectedItem());
                    String Sem = BGsem.getSelection().getActionCommand();
                    String gradeLvl = String.valueOf(cmbGradeLevel.getSelectedItem());
                    String Section = String.valueOf(cmbSection.getSelectedItem());
                    String Strand = String.valueOf(cmbStrand.getSelectedItem());
                    String Adviser = "None for now";
                    String Remarks = BGremarksSHS.getSelection().getActionCommand();
                    
                    Object[] data = {SY, Sem, Section,
                                 gradeLvl, Strand, Remarks, Adviser};
                    DefaultTableModel shsModel = (DefaultTableModel) tblSHS.getModel();
                    shsModel.addRow(data);
                }
            }
        }else{
            // update block to work for SQL
            int Option = JOptionPane.showConfirmDialog(null, "Update Senior-High Data to Table?", "Updating..", JOptionPane.YES_NO_OPTION);
            
            if(Option == 0){
                didClick = false;
                data.clear();
                if((BGsem.isSelected(rbSem1.getModel()) == false && BGsem.isSelected(rbSem2.getModel()) == false)|| 
              (BGremarksSHS.isSelected(rbCompleter.getModel()) == false && BGremarksSHS.isSelected(rbIrregular.getModel()) == false)){
                    
                    JOptionPane.showMessageDialog(this, "One of the fields are null/left blank.", "Invalid Field", 
                    JOptionPane.INFORMATION_MESSAGE);
                }else{
                    String SY = String.valueOf(cmbYearSHS.getSelectedItem());
                    String Sem = BGsem.getSelection().getActionCommand();
                    String gradeLvl = String.valueOf(cmbGradeLevel.getSelectedItem());
                    String Section = String.valueOf(cmbSection.getSelectedItem());
                    String Strand = String.valueOf(cmbStrand.getSelectedItem());
                    String Adviser = "None for now";
                    String Remarks = BGremarksSHS.getSelection().getActionCommand();
                    
                    
                    // Add a condition if the previous data is the same as the new data
                    // Then dont do anythin
                    Object[] newData = {SY, Sem, Section,
                                 gradeLvl, Strand, Remarks, Adviser};
                    DefaultTableModel shsModel = (DefaultTableModel) tblSHS.getModel();
                    
                    for(int i = 0; i < shsModel.getColumnCount();i++){
                        shsModel.setValueAt(newData[i], pointAt, i);
                    }
                    panelEditinglbl.setVisible(false);
                    lblEdit.setVisible(false);
                    lblRow.setVisible(false);
                    btnAdd.setText("Add");
                    btnCancel.setVisible(false);
                    shsActionBar.setBorder(shsAbarTxt[0]);
                    cmbYearSHS.setSelectedIndex(YearArr.getArrEndIndex());
                    cmbSection.setSelectedIndex(0);
                    cmbGradeLevel.setSelectedIndex(0);
                    cmbStrand.setSelectedIndex(0);
                    BGsem.clearSelection();
                    BGremarksSHS.clearSelection();
                }
            }
            
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void rbCompleterJHSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCompleterJHSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbCompleterJHSActionPerformed

    private void tblJHSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblJHSMouseClicked
        // TODO add your handling code here:
        jhsActionBar.setBorder(shsAbarTxt[1]);
        btnAddJHS.setText("Update");
        btnCancelJHS.setVisible(true);
    }//GEN-LAST:event_tblJHSMouseClicked

    private void btnCancelJHSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelJHSActionPerformed
        // TODO add your handling code here:
        btnAddJHS.setText("Add");
        jhsActionBar.setBorder(jhsAbarTxt[0]);
        btnCancelJHS.setVisible(false);
        
    }//GEN-LAST:event_btnCancelJHSActionPerformed

    private void cmbGradeLevelJHSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbGradeLevelJHSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbGradeLevelJHSActionPerformed

    private void cmbSchoolNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSchoolNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSchoolNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BGremarksJHS;
    private javax.swing.ButtonGroup BGremarksSHS;
    private javax.swing.ButtonGroup BGsem;
    private javax.swing.ButtonGroup BGtransferred;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAddJHS;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCancelJHS;
    private javax.swing.JComboBox<String> cmbAdviser;
    private javax.swing.JComboBox<String> cmbGradeLevel;
    private javax.swing.JComboBox<String> cmbGradeLevelJHS;
    private javax.swing.JLabel cmbRemarksJHS;
    private javax.swing.JComboBox<String> cmbSchoolName;
    private javax.swing.JComboBox<String> cmbSection;
    private javax.swing.JComboBox<String> cmbStrand;
    private javax.swing.JComboBox<String> cmbYearJHS;
    private javax.swing.JComboBox<String> cmbYearSHS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel jhsActionBar;
    private javax.swing.JLabel lblAdviser;
    private javax.swing.JLabel lblAdviserJHS;
    private javax.swing.JLabel lblBirthStreetAddr21;
    private javax.swing.JLabel lblEdit;
    private javax.swing.JLabel lblGradeLevel;
    private javax.swing.JLabel lblGradeLevelJHS;
    private javax.swing.JLabel lblRemarks;
    private javax.swing.JLabel lblRow;
    private javax.swing.JLabel lblSY;
    private javax.swing.JLabel lblSchoolName;
    private javax.swing.JLabel lblSection;
    private javax.swing.JLabel lblSectionJHS;
    private javax.swing.JLabel lblSem;
    private javax.swing.JLabel lblStrand;
    private javax.swing.JLabel lblTransferred;
    private javax.swing.JPanel panelEditinglbl;
    private javax.swing.JRadioButton rbCompleter;
    private javax.swing.JRadioButton rbCompleterJHS;
    private javax.swing.JRadioButton rbIrregular;
    private javax.swing.JRadioButton rbRepeaterJHS;
    private javax.swing.JRadioButton rbSem1;
    private javax.swing.JRadioButton rbSem2;
    private javax.swing.JRadioButton rbTransIN;
    private javax.swing.JRadioButton rbTransOut;
    private javax.swing.JPanel shsActionBar;
    private javax.swing.JPanel tabbedJHS;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JPanel tabbedSHS;
    private javax.swing.JTable tblJHS;
    private javax.swing.JTable tblSHS;
    private javax.swing.JPanel top;
    private javax.swing.JTextField txtAdviser;
    private javax.swing.JTextField txtSection;
    // End of variables declaration//GEN-END:variables
}
