package Form;

import Processor.*;
import Tabbed.TabbedForm;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author blesDev
 */
public class Masterlist extends TabbedForm {
    private final FlatSVGIcon searchIcon = new FlatSVGIcon("Drawer/Icon/search.svg", 32, 32);
    private final Misc.schoolYear YearArr = new Misc.schoolYear();
    /**
     * Creates new form TestForm
     */
   
    
    public Masterlist() {
        initComponents();
        YearArr.setMark(2000);
        // Radio Buttons
        rbSem1.setActionCommand("1st");
        rbSem2.setActionCommand("2nd");
        rbG11.setActionCommand("11");
        rbG12.setActionCommand("12");
        // ComboBoxes
        cmbYear.setModel(new DefaultComboBoxModel<>((String[]) YearArr.getYearArr().toArray(new String[0])));
        cmbYear.setSelectedIndex(YearArr.getArrEndIndex());
        // Buttons
        btnSearch.setOpaque(false);
        btnSearch.setBorderPainted(false);
        btnSearch.setContentAreaFilled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg1 = new javax.swing.ButtonGroup();
        bg2 = new javax.swing.ButtonGroup();
        topBar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        panelSearchBar = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        lblSchoolYear = new javax.swing.JLabel();
        lblSem = new javax.swing.JLabel();
        rbSem1 = new javax.swing.JRadioButton();
        lblGradeLevel = new javax.swing.JLabel();
        rbG11 = new javax.swing.JRadioButton();
        rbSem2 = new javax.swing.JRadioButton();
        rbG12 = new javax.swing.JRadioButton();
        lblStrand = new javax.swing.JLabel();
        cmbStrand = new javax.swing.JComboBox<>();
        cmbSection = new javax.swing.JComboBox<>();
        lblSection = new javax.swing.JLabel();
        cmbYear = new javax.swing.JComboBox<>();
        btnSearch = new javax.swing.JButton();
        panelCountBar = new javax.swing.JPanel();
        lblFemale = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        lblMale = new javax.swing.JLabel();
        txtOverallCount = new javax.swing.JTextField();
        txtFemaleCount = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        txtMaleCount = new javax.swing.JTextField();
        panelAdviser = new javax.swing.JPanel();
        txtAdviserName = new javax.swing.JTextField();
        lblAdviser = new javax.swing.JLabel();
        panelTable = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblFemale = new javax.swing.JTable();
        lblFemaleTable = new javax.swing.JLabel();
        lblMaleTable = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblMale = new javax.swing.JTable();

        setBackground(new java.awt.Color(0, 171, 65));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        topBar.setBackground(new java.awt.Color(0, 134, 49));
        topBar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        topBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Transparent.png"))); // NOI18N
        topBar.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 20, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Mnhs_transSmall.png"))); // NOI18N
        topBar.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, -1, -1));

        jLabel4.setFont(new java.awt.Font("Cambria", 3, 55)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Class Masterlist");
        topBar.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 400, 90));

        add(topBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1300, 130));

        panelSearchBar.setBackground(new java.awt.Color(0, 134, 49));
        panelSearchBar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelSearchBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(0, 134, 49));
        jPanel8.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), "Search By", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(255, 255, 255)))); // NOI18N
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSchoolYear.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblSchoolYear.setForeground(new java.awt.Color(255, 255, 255));
        lblSchoolYear.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSchoolYear.setText("School Year");
        jPanel8.add(lblSchoolYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 70, 20));

        lblSem.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblSem.setForeground(new java.awt.Color(255, 255, 255));
        lblSem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSem.setText("Semester");
        jPanel8.add(lblSem, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 80, 20));

        bg2.add(rbSem1);
        rbSem1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        rbSem1.setForeground(new java.awt.Color(255, 255, 255));
        rbSem1.setText("1st");
        rbSem1.setName("1st"); // NOI18N
        jPanel8.add(rbSem1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 50, -1));

        lblGradeLevel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblGradeLevel.setForeground(new java.awt.Color(255, 255, 255));
        lblGradeLevel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGradeLevel.setText("Grade Level");
        jPanel8.add(lblGradeLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 80, 20));

        bg1.add(rbG11);
        rbG11.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        rbG11.setForeground(new java.awt.Color(255, 255, 255));
        rbG11.setText("11");
        jPanel8.add(rbG11, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 40, -1));

        bg2.add(rbSem2);
        rbSem2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        rbSem2.setForeground(new java.awt.Color(255, 255, 255));
        rbSem2.setText("2nd");
        rbSem2.setName("2nd"); // NOI18N
        jPanel8.add(rbSem2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 50, -1));

        bg1.add(rbG12);
        rbG12.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        rbG12.setForeground(new java.awt.Color(255, 255, 255));
        rbG12.setText("12");
        jPanel8.add(rbG12, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 40, -1));

        lblStrand.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblStrand.setForeground(new java.awt.Color(255, 255, 255));
        lblStrand.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStrand.setText("Strand");
        jPanel8.add(lblStrand, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 80, 20));

        cmbStrand.setBackground(new java.awt.Color(192, 245, 182));
        cmbStrand.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cmbStrand.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "I.C.T", "S.T.E.M", "G.A.S", "G.A.S - ABM", "H.E", "A.D.A.S" }));
        cmbStrand.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel8.add(cmbStrand, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 80, 20));

        cmbSection.setBackground(new java.awt.Color(192, 245, 182));
        cmbSection.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cmbSection.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15" }));
        cmbSection.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel8.add(cmbSection, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, 60, 20));

        lblSection.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lblSection.setForeground(new java.awt.Color(255, 255, 255));
        lblSection.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSection.setText("Section");
        jPanel8.add(lblSection, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 60, 20));

        cmbYear.setBackground(new java.awt.Color(192, 245, 182));
        cmbYear.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel8.add(cmbYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 110, 20));

        panelSearchBar.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 590, 60));

        btnSearch.setIcon(searchIcon);
        btnSearch.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSearchMouseExited(evt);
            }
        });
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        panelSearchBar.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 20, 60, 40));

        add(panelSearchBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 690, 80));

        panelCountBar.setBackground(new java.awt.Color(0, 134, 49));
        panelCountBar.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(), javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), "Class Headcount", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(255, 255, 255)))); // NOI18N
        panelCountBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFemale.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblFemale.setForeground(new java.awt.Color(255, 255, 255));
        lblFemale.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFemale.setText("Female");
        panelCountBar.add(lblFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 70, 30));

        lblTotal.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(255, 255, 255));
        lblTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotal.setText("Total");
        panelCountBar.add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 70, 30));

        lblMale.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblMale.setForeground(new java.awt.Color(255, 255, 255));
        lblMale.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMale.setText("Male");
        panelCountBar.add(lblMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 50, 30));

        txtOverallCount.setEditable(false);
        txtOverallCount.setBackground(new java.awt.Color(255, 255, 255));
        txtOverallCount.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        panelCountBar.add(txtOverallCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 50, 30));

        txtFemaleCount.setEditable(false);
        txtFemaleCount.setBackground(new java.awt.Color(255, 255, 255));
        txtFemaleCount.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        panelCountBar.add(txtFemaleCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 50, 30));

        jPanel6.setBackground(new java.awt.Color(24, 134, 45));
        jPanel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Female");
        jPanel6.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 70, 30));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Total:");
        jPanel6.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 60, 40));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Male");
        jPanel6.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 50, 30));

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jPanel6.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 50, 40));

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jPanel6.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 50, 40));

        jPanel7.setBackground(new java.awt.Color(24, 134, 45));
        jPanel7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Female");
        jPanel7.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 70, 30));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Total:");
        jPanel7.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 60, 40));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Male");
        jPanel7.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 50, 30));

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jPanel7.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 50, 40));

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        jPanel7.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 50, 40));

        jPanel6.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 140, 200, 80));

        panelCountBar.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 140, 200, 80));

        txtMaleCount.setEditable(false);
        txtMaleCount.setBackground(new java.awt.Color(255, 255, 255));
        txtMaleCount.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        panelCountBar.add(txtMaleCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 50, 30));

        add(panelCountBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 140, 210, 80));

        panelAdviser.setBackground(new java.awt.Color(0, 134, 49));
        panelAdviser.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelAdviser.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtAdviserName.setEditable(false);
        txtAdviserName.setBackground(new java.awt.Color(255, 255, 255));
        txtAdviserName.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        panelAdviser.add(txtAdviserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 260, 30));

        lblAdviser.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblAdviser.setForeground(new java.awt.Color(255, 255, 255));
        lblAdviser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAdviser.setText("Adviser");
        panelAdviser.add(lblAdviser, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 90, 30));

        add(panelAdviser, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 140, 280, 80));

        panelTable.setBackground(new java.awt.Color(0, 134, 49));
        panelTable.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelTable.setForeground(new java.awt.Color(0, 134, 49));
        panelTable.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblFemale.setBackground(new java.awt.Color(153, 255, 153));
        tblFemale.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tblFemale.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tblFemale.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ULRN", "Full Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblFemale.setCellSelectionEnabled(true);
        tblFemale.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        tblFemale.setGridColor(new java.awt.Color(0, 134, 49));
        tblFemale.setSelectionBackground(new java.awt.Color(153, 204, 255));
        tblFemale.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblFemale.setShowGrid(true);
        tblFemale.getTableHeader().setResizingAllowed(false);
        tblFemale.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tblFemale);

        panelTable.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 40, 590, 310));

        lblFemaleTable.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblFemaleTable.setForeground(new java.awt.Color(255, 255, 255));
        lblFemaleTable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFemaleTable.setText("Female");
        panelTable.add(lblFemaleTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 0, 80, 40));

        lblMaleTable.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblMaleTable.setForeground(new java.awt.Color(255, 255, 255));
        lblMaleTable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMaleTable.setText("Male");
        panelTable.add(lblMaleTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 80, 40));

        tblMale.setBackground(new java.awt.Color(153, 255, 153));
        tblMale.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tblMale.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        tblMale.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ULRN", "Full Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMale.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        tblMale.setGridColor(new java.awt.Color(0, 134, 49));
        tblMale.setSelectionBackground(new java.awt.Color(153, 204, 255));
        tblMale.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblMale.setShowGrid(true);
        tblMale.getTableHeader().setResizingAllowed(false);
        tblMale.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(tblMale);

        panelTable.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 590, 310));

        add(panelTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 1220, 380));
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
//        try {
//            if((bg2.isSelected(rbSem1.getModel()) == false && bg2.isSelected(rbSem2.getModel()) == false) 
//                || (bg1.isSelected(rbG11.getModel()) == false && bg1.isSelected(rbG12.getModel()) == false)){
//                JOptionPane.showMessageDialog(this, "One of the fields are null/left blank.", 
//                        "Invalid Field", JOptionPane.INFORMATION_MESSAGE);
//            }else{
//                String SY = Arrays.toString(cmbYear.getSelectedObjects());
//                String Strand = cmbStrand.getSelectedItem().toString();
//                String Section = cmbSection.getSelectedItem().toString();
//                String Sem = bg2.getSelection().getActionCommand();
//                String Grlvl = bg1.getSelection().getActionCommand();
//                // Fix this luke
//                // Fix this luke
//                
//                        
//                Object[] data = {ULRN, Full_Name};
//                DefaultTableModel maleTable = (DefaultTableModel) tblSHS.getModel();
//                maleTable.addRow(data);
//                }
//                
//            
//        } catch (SQLException ex) {
//            Logger.getLogger(Masterlist.class.getName()).log(Level.SEVERE, null, ex);
//        }
        
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnSearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseEntered
        // TODO add your handling code here:
        btnSearch.setIcon(new FlatSVGIcon("Drawer/Icon/searchShift.svg", 32, 32));
    }//GEN-LAST:event_btnSearchMouseEntered

    private void btnSearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseExited
        // TODO add your handling code here:
        btnSearch.setIcon(searchIcon);
    }//GEN-LAST:event_btnSearchMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg1;
    private javax.swing.ButtonGroup bg2;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> cmbSection;
    private javax.swing.JComboBox<String> cmbStrand;
    private javax.swing.JComboBox<String> cmbYear;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JLabel lblAdviser;
    private javax.swing.JLabel lblFemale;
    private javax.swing.JLabel lblFemaleTable;
    private javax.swing.JLabel lblGradeLevel;
    private javax.swing.JLabel lblMale;
    private javax.swing.JLabel lblMaleTable;
    private javax.swing.JLabel lblSchoolYear;
    private javax.swing.JLabel lblSection;
    private javax.swing.JLabel lblSem;
    private javax.swing.JLabel lblStrand;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JPanel panelAdviser;
    private javax.swing.JPanel panelCountBar;
    private javax.swing.JPanel panelSearchBar;
    private javax.swing.JPanel panelTable;
    private javax.swing.JRadioButton rbG11;
    private javax.swing.JRadioButton rbG12;
    private javax.swing.JRadioButton rbSem1;
    private javax.swing.JRadioButton rbSem2;
    private javax.swing.JTable tblFemale;
    private javax.swing.JTable tblMale;
    private javax.swing.JPanel topBar;
    private javax.swing.JTextField txtAdviserName;
    private javax.swing.JTextField txtFemaleCount;
    private javax.swing.JTextField txtMaleCount;
    private javax.swing.JTextField txtOverallCount;
    // End of variables declaration//GEN-END:variables
}
