package Form;

import Processor.*;
import Tabbed.TabbedForm;
import java.sql.SQLException;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author blesDev
 */
public class PersonalInfo extends TabbedForm {
    public final int ULRNlimit = 12;
    /**
     * Creates new form TestForm
     * @throws java.sql.SQLException
     */
    public PersonalInfo(){
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCalendar1 = new com.toedter.calendar.JCalendar();
        TopBar = new javax.swing.JPanel();
        StumsIcon = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        ico1 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        panelULRN = new javax.swing.JPanel();
        lblUlrn = new javax.swing.JLabel();
        txtULRN = new javax.swing.JTextField();
        personalDetails = new javax.swing.JPanel();
        BdayPanelTXT1 = new javax.swing.JPanel();
        lblContact = new javax.swing.JLabel();
        txtContact = new javax.swing.JTextField();
        lblFirstName = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        lblSuffix = new javax.swing.JLabel();
        countryCode = new javax.swing.JComboBox<>();
        lblMiddleName = new javax.swing.JLabel();
        txtMiddleName = new javax.swing.JTextField();
        lblGender = new javax.swing.JLabel();
        cmbNationality = new javax.swing.JComboBox<>();
        lblBday1 = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        lblNationality = new javax.swing.JLabel();
        cmbGender = new javax.swing.JComboBox<>();
        cmbSuffix = new javax.swing.JComboBox<>();
        Addresses = new javax.swing.JPanel();
        BdayPanelTXT = new javax.swing.JPanel();
        lblBirthCity = new javax.swing.JLabel();
        cmbBirthCity = new javax.swing.JComboBox<>();
        lblBirthProv = new javax.swing.JLabel();
        cmbBirthProv = new javax.swing.JComboBox<>();
        CaddressPaneltxt = new javax.swing.JPanel();
        lblBrgy = new javax.swing.JLabel();
        cmbBarangay = new javax.swing.JComboBox<>();
        lblBirthProv2 = new javax.swing.JLabel();
        cmbBirthProv1 = new javax.swing.JComboBox<>();
        cmbCity = new javax.swing.JComboBox<>();
        txtFirstName3 = new javax.swing.JTextField();
        lblCity = new javax.swing.JLabel();
        txtStreetAddr = new javax.swing.JTextField();
        lblBirthProv1 = new javax.swing.JLabel();
        lblStreetAddr = new javax.swing.JLabel();
        familyDetails = new javax.swing.JPanel();
        CaddressPaneltxt2 = new javax.swing.JPanel();
        txtFirstName11 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txtContact3 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txtContact4 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        txtFirstName8 = new javax.swing.JTextField();
        CaddressPaneltxt1 = new javax.swing.JPanel();
        txtContact5 = new javax.swing.JTextField();
        txtContact2 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtFirstName10 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(0, 171, 65));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TopBar.setBackground(new java.awt.Color(0, 134, 49));
        TopBar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        TopBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        StumsIcon.setBackground(new java.awt.Color(0, 153, 51));
        StumsIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Transparent.png"))); // NOI18N
        TopBar.add(StumsIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 20, -1, -1));

        lblTitle.setFont(new java.awt.Font("Cambria", 3, 55)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Student Personal Information");
        TopBar.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 750, 80));

        ico1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Mnhs_transSmall.png"))); // NOI18N
        TopBar.add(ico1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        add(TopBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1260, 130));

        btnAdd.setBackground(new java.awt.Color(0, 134, 49));
        btnAdd.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Add");
        btnAdd.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAddMouseExited(evt);
            }
        });
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 100, 30));

        panelULRN.setBackground(new java.awt.Color(0, 134, 49));
        panelULRN.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelULRN.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUlrn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblUlrn.setForeground(new java.awt.Color(255, 255, 255));
        lblUlrn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUlrn.setText("ULRN");
        panelULRN.add(lblUlrn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 50, 30));

        txtULRN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtULRN.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtULRN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtULRNKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtULRNKeyTyped(evt);
            }
        });
        panelULRN.add(txtULRN, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 230, 30));

        add(panelULRN, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 290, 50));

        personalDetails.setBackground(new java.awt.Color(0, 134, 49));
        personalDetails.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        personalDetails.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BdayPanelTXT1.setBackground(new java.awt.Color(0, 134, 49));
        BdayPanelTXT1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "Personal Details", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        BdayPanelTXT1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblContact.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblContact.setForeground(new java.awt.Color(255, 255, 255));
        lblContact.setText("Contact No.");
        BdayPanelTXT1.add(lblContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        txtContact.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        BdayPanelTXT1.add(txtContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 180, 30));

        lblFirstName.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblFirstName.setForeground(new java.awt.Color(255, 255, 255));
        lblFirstName.setText("First Name");
        BdayPanelTXT1.add(lblFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        txtFirstName.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        BdayPanelTXT1.add(txtFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 240, 30));

        lblSuffix.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblSuffix.setForeground(new java.awt.Color(255, 255, 255));
        lblSuffix.setText("Suffix");
        BdayPanelTXT1.add(lblSuffix, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, -1, -1));

        countryCode.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        countryCode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "+63" }));
        BdayPanelTXT1.add(countryCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 60, 30));

        lblMiddleName.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblMiddleName.setForeground(new java.awt.Color(255, 255, 255));
        lblMiddleName.setText("Middle Name");
        BdayPanelTXT1.add(lblMiddleName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        txtMiddleName.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        BdayPanelTXT1.add(txtMiddleName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 240, 30));

        lblGender.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblGender.setForeground(new java.awt.Color(255, 255, 255));
        lblGender.setText("Gender");
        BdayPanelTXT1.add(lblGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 60, -1));

        cmbNationality.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        BdayPanelTXT1.add(cmbNationality, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 130, 30));

        lblBday1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblBday1.setForeground(new java.awt.Color(255, 255, 255));
        lblBday1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBday1.setText("birthday");
        BdayPanelTXT1.add(lblBday1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 210, 20));

        lblLastName.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblLastName.setForeground(new java.awt.Color(255, 255, 255));
        lblLastName.setText("Last Name");
        BdayPanelTXT1.add(lblLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        txtLastName.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        BdayPanelTXT1.add(txtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 240, 30));

        lblNationality.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblNationality.setForeground(new java.awt.Color(255, 255, 255));
        lblNationality.setText("Nationality");
        BdayPanelTXT1.add(lblNationality, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, -1, -1));

        cmbGender.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cmbGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Preferred not to say" }));
        BdayPanelTXT1.add(cmbGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 130, 30));

        cmbSuffix.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cmbSuffix.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "N/A", "Jr.", "Sr.", "I", "II", "III", "IV", "V" }));
        BdayPanelTXT1.add(cmbSuffix, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 130, 30));

        personalDetails.add(BdayPanelTXT1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 410, 300));

        add(personalDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 430, 320));

        Addresses.setBackground(new java.awt.Color(0, 134, 49));
        Addresses.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Addresses.setForeground(new java.awt.Color(255, 255, 255));
        Addresses.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BdayPanelTXT.setBackground(new java.awt.Color(0, 134, 49));
        BdayPanelTXT.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "Birthplace", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        BdayPanelTXT.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBirthCity.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblBirthCity.setForeground(new java.awt.Color(255, 255, 255));
        lblBirthCity.setText("City");
        BdayPanelTXT.add(lblBirthCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 30, 30));

        cmbBirthCity.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cmbBirthCity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        BdayPanelTXT.add(cmbBirthCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 130, 30));

        lblBirthProv.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblBirthProv.setForeground(new java.awt.Color(255, 255, 255));
        lblBirthProv.setText("Province");
        BdayPanelTXT.add(lblBirthProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, 30));

        cmbBirthProv.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cmbBirthProv.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        BdayPanelTXT.add(cmbBirthProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 130, 30));

        Addresses.add(BdayPanelTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 330, 90));

        CaddressPaneltxt.setBackground(new java.awt.Color(0, 134, 49));
        CaddressPaneltxt.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "Home Address", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        CaddressPaneltxt.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBrgy.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblBrgy.setForeground(new java.awt.Color(255, 255, 255));
        lblBrgy.setText("Barangay");
        CaddressPaneltxt.add(lblBrgy, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, -1, 30));

        cmbBarangay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CaddressPaneltxt.add(cmbBarangay, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 140, 30));

        lblBirthProv2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblBirthProv2.setForeground(new java.awt.Color(255, 255, 255));
        lblBirthProv2.setText("Province");
        CaddressPaneltxt.add(lblBirthProv2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, 30));

        cmbBirthProv1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Metro Manila" }));
        CaddressPaneltxt.add(cmbBirthProv1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 140, 30));

        cmbCity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Putatan Muntinlupa", " " }));
        CaddressPaneltxt.add(cmbCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 140, 30));
        CaddressPaneltxt.add(txtFirstName3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 140, 30));

        lblCity.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblCity.setForeground(new java.awt.Color(255, 255, 255));
        lblCity.setText("City");
        CaddressPaneltxt.add(lblCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, 30));
        CaddressPaneltxt.add(txtStreetAddr, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 310, 30));

        lblBirthProv1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblBirthProv1.setForeground(new java.awt.Color(255, 255, 255));
        lblBirthProv1.setText("Zip Code");
        CaddressPaneltxt.add(lblBirthProv1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, -1, 30));

        lblStreetAddr.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblStreetAddr.setForeground(new java.awt.Color(255, 255, 255));
        lblStreetAddr.setText("Street Address");
        CaddressPaneltxt.add(lblStreetAddr, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 110, 30));

        Addresses.add(CaddressPaneltxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 330, 320));

        add(Addresses, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, 350, 440));

        familyDetails.setBackground(new java.awt.Color(0, 134, 49));
        familyDetails.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        familyDetails.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CaddressPaneltxt2.setBackground(new java.awt.Color(0, 134, 49));
        CaddressPaneltxt2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "Parent's Details", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        CaddressPaneltxt2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        CaddressPaneltxt2.add(txtFirstName11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 310, 30));

        jLabel27.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Mother's Maiden Name");
        CaddressPaneltxt2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 30));
        CaddressPaneltxt2.add(txtContact3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 310, 30));

        jLabel32.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Mother's Contact No.");
        CaddressPaneltxt2.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 30));

        jLabel25.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Father's Contact No.");
        CaddressPaneltxt2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, 30));
        CaddressPaneltxt2.add(txtContact4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 310, 30));

        jLabel30.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Father's Maiden Name");
        CaddressPaneltxt2.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, 30));
        CaddressPaneltxt2.add(txtFirstName8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 310, 30));

        familyDetails.add(CaddressPaneltxt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 350, 270));

        CaddressPaneltxt1.setBackground(new java.awt.Color(0, 134, 49));
        CaddressPaneltxt1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "Guardian's Details", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        CaddressPaneltxt1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        CaddressPaneltxt1.add(txtContact5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 200, 30));
        CaddressPaneltxt1.add(txtContact2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 200, 30));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Guardian's Name");
        CaddressPaneltxt1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 30));

        jLabel33.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Guardian's Contact No.");
        CaddressPaneltxt1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 30));

        jLabel26.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("No. of Siblings");
        CaddressPaneltxt1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 110, 30));
        CaddressPaneltxt1.add(txtFirstName10, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 110, 30));

        familyDetails.add(CaddressPaneltxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 350, 150));

        add(familyDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 150, 370, 440));
    }// </editor-fold>//GEN-END:initComponents

    private void txtULRNKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtULRNKeyTyped
        // This block of code limits the numbers typed by the user
        int Len = txtULRN.getText().length();
        try {
             Integer.parseInt(String.valueOf(evt.getKeyChar()));
        } catch (NumberFormatException z) {
            evt.consume();
        }
        if(Len >= ULRNlimit){
            evt.consume();
        }
    }//GEN-LAST:event_txtULRNKeyTyped

    private void btnAddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseEntered
        // Hover color
    }//GEN-LAST:event_btnAddMouseEntered

    private void btnAddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseExited
        // Hover color
    }//GEN-LAST:event_btnAddMouseExited

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // Later
    }//GEN-LAST:event_btnAddActionPerformed

    private void txtULRNKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtULRNKeyPressed
        // TODO add your handling code here:
        final int key_enter = 10;
        int Len = txtULRN.getText().length();
        
        if(Len == ULRNlimit && evt.getKeyCode() == key_enter){
            // Retrieve data from sql and..
            // Display it on the stuff
        }
    }//GEN-LAST:event_txtULRNKeyPressed
 
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Addresses;
    private javax.swing.JPanel BdayPanelTXT;
    private javax.swing.JPanel BdayPanelTXT1;
    private javax.swing.JPanel CaddressPaneltxt;
    private javax.swing.JPanel CaddressPaneltxt1;
    private javax.swing.JPanel CaddressPaneltxt2;
    private javax.swing.JLabel StumsIcon;
    private javax.swing.JPanel TopBar;
    private javax.swing.JButton btnAdd;
    private javax.swing.JComboBox<String> cmbBarangay;
    private javax.swing.JComboBox<String> cmbBirthCity;
    private javax.swing.JComboBox<String> cmbBirthProv;
    private javax.swing.JComboBox<String> cmbBirthProv1;
    private javax.swing.JComboBox<String> cmbCity;
    private javax.swing.JComboBox<String> cmbGender;
    private javax.swing.JComboBox<String> cmbNationality;
    private javax.swing.JComboBox<String> cmbSuffix;
    private javax.swing.JComboBox<String> countryCode;
    private javax.swing.JPanel familyDetails;
    private javax.swing.JLabel ico1;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel lblBday1;
    private javax.swing.JLabel lblBirthCity;
    private javax.swing.JLabel lblBirthProv;
    private javax.swing.JLabel lblBirthProv1;
    private javax.swing.JLabel lblBirthProv2;
    private javax.swing.JLabel lblBrgy;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblContact;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblMiddleName;
    private javax.swing.JLabel lblNationality;
    private javax.swing.JLabel lblStreetAddr;
    private javax.swing.JLabel lblSuffix;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUlrn;
    private javax.swing.JPanel panelULRN;
    private javax.swing.JPanel personalDetails;
    private javax.swing.JTextField txtContact;
    private javax.swing.JTextField txtContact2;
    private javax.swing.JTextField txtContact3;
    private javax.swing.JTextField txtContact4;
    private javax.swing.JTextField txtContact5;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtFirstName10;
    private javax.swing.JTextField txtFirstName11;
    private javax.swing.JTextField txtFirstName3;
    private javax.swing.JTextField txtFirstName8;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtMiddleName;
    private javax.swing.JTextField txtStreetAddr;
    private javax.swing.JTextField txtULRN;
    // End of variables declaration//GEN-END:variables
}
